version: '3.1'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ADMINUSER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ADMINPASS}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_ADMINUSER}:${DB_ADMINPASS}@mongo:27017/
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMINUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMINPASS}
    ports:
      - '27017:27017'
    volumes:
      - ${DB_USER_VOLUME}
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
